# Generated by Django 5.2 on 2025-05-06 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0002_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='location',
        ),
        migrations.AddField(
            model_name='theater',
            name='location',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
