# Generated by Django 5.2 on 2025-05-06 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0003_delete_location_theater_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='theater',
            name='city_name',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.city'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.state'),
        ),
    ]
