# Generated by Django 5.2 on 2025-05-06 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0004_city_state_theater_city_name_city_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='city_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='state',
            old_name='state',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='theater',
            old_name='city_name',
            new_name='city',
        ),
    ]
