# Generated by Django 5.2 on 2025-05-07 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0007_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='language',
            new_name='name',
        ),
    ]
