# Generated by Django 5.2 on 2025-05-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0008_rename_language_language_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seat',
            name='show',
        ),
        migrations.AddField(
            model_name='seat',
            name='theater',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.theater'),
            preserve_default=False,
        ),
    ]
