# Generated by Django 5.2 on 2025-05-09 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0010_remove_seat_is_booked_booking_theater'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='Bookinginfo',
        ),
        migrations.CreateModel(
            name='Booking_show_seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.bookinginfo')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.show')),
            ],
            options={
                'unique_together': {('show', 'seat')},
            },
        ),
        migrations.AddField(
            model_name='show',
            name='seats',
            field=models.ManyToManyField(through='ticket_booking.Booking_show_seat', to='ticket_booking.seat'),
        ),
    ]
