# Generated by Django 5.2 on 2025-05-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0011_rename_booking_bookinginfo_booking_show_seat_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking_show_seat',
            new_name='Show_seat_booking',
        ),
        migrations.RemoveField(
            model_name='bookinginfo',
            name='seats',
        ),
        migrations.RemoveField(
            model_name='bookinginfo',
            name='show',
        ),
    ]
