# Generated by Django 5.2 on 2025-05-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0012_rename_booking_show_seat_show_seat_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
