# Generated by Django 5.2 on 2025-05-09 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0013_bookinginfo_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='show',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.show'),
            preserve_default=False,
        ),
    ]
