# Generated by Django 5.2 on 2025-05-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0014_bookinginfo_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show_seat_booking',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='show_seat_booking',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
