# Generated by Django 5.2 on 2025-05-11 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0015_show_seat_booking_is_booked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='show_seat_booking',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='show_seat_booking',
            name='booking_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.bookinginfo'),
        ),
    ]
