# Generated by Django 5.2 on 2025-05-13 11:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0017_seatlocksession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seatlocksession',
            name='is_locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='seatlocksession',
            name='locked_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='ShowSeatBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_booked', models.BooleanField(default=False)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('booking_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.bookinginfo')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.seat')),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.show')),
            ],
            options={
                'unique_together': {('show', 'seat')},
            },
        ),
        migrations.AlterField(
            model_name='show',
            name='seats',
            field=models.ManyToManyField(through='ticket_booking.ShowSeatBooking', to='ticket_booking.seat'),
        ),
        migrations.DeleteModel(
            name='Show_seat_booking',
        ),
    ]
