# Generated by Django 5.2 on 2025-05-13 12:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0018_alter_seatlocksession_is_locked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='showseatbooking',
            name='session_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.session'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SeatLockSession',
        ),
    ]
