# Generated by Django 5.2 on 2025-05-14 10:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0019_session_showseatbooking_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showseatbooking',
            name='booked_at',
        ),
        migrations.AlterField(
    model_name='session',
    name='created_at',
    field=models.DateTimeField(auto_now_add=True),
),

        migrations.AddField(
            model_name='showseatbooking',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
