# Generated by Django 5.2 on 2025-05-14 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0020_remove_showseatbooking_booked_at_session_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='created_at',
        ),
    ]
