# Generated by Django 5.2 on 2025-05-14 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0023_showseatbooking_booked_at_showseatbooking_locked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showseatbooking',
            name='booked_at',
        ),
        migrations.RemoveField(
            model_name='showseatbooking',
            name='locked_at',
        ),
    ]
