# Generated by Django 5.2 on 2025-05-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0024_remove_showseatbooking_booked_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showseatbooking',
            old_name='booking_info',
            new_name='bookinginfo',
        ),
    ]
