# Generated by Django 5.2 on 2025-05-14 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0025_rename_booking_info_showseatbooking_bookinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showseatbooking',
            name='bookinginfo',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.bookinginfo'),
            preserve_default=False,
        ),
    ]
