# Generated by Django 5.2 on 2025-05-14 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0026_alter_showseatbooking_bookinginfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showseatbooking',
            name='bookinginfo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.bookinginfo'),
        ),
    ]
