# Generated by Django 5.2 on 2025-05-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0027_alter_showseatbooking_bookinginfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showseatbooking',
            old_name='bookinginfo',
            new_name='Bookinginfo',
        ),
    ]
