# Generated by Django 5.2 on 2025-05-15 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0028_rename_bookinginfo_showseatbooking_bookinginfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showseatbooking',
            old_name='Bookinginfo',
            new_name='bookinginfo',
        ),
    ]
