# Generated by Django 5.2 on 2025-05-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0029_rename_bookinginfo_showseatbooking_bookinginfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket_booking.language'),
            preserve_default=False,
        ),
    ]
