# Generated by Django 5.2 on 2025-06-03 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_booking', '0030_show_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinginfo',
            name='seats',
            field=models.ManyToManyField(to='ticket_booking.seat'),
        ),
    ]
